# Generated by Django 5.0 on 2024-12-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
